[package]
name = "array_try_map"
version = "0.1.0"
authors = ["DrMeepster"]
edition = "2018"
description = "Adds a try_map method to arrays."
readme = "README.md"
repository = "https://github.com/DrMeepster/array_try_map/"
license = "MIT OR Apache-2.0"
keywords = ["array"]
categories = ["no-std"]