[package]
name = "array_try_map"
version = "0.1.0"
authors = ["DrMeepster <19316085+DrMeepster@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
