name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: repo 
      - name: Checkout docs
        uses: actions/checkout@v2
        with:
          ref: docs
          path: docs
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - run: |
          cd repo
          cargo test
          cargo doc
          cp -r target/doc/* $GITHUB_WORKSPACE/docs/
      - uses: EndBug/add-and-commit@v5
        with:
          branch: docs
          path: docs
          message: "documentation update" 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
